import pandas as pd
import random
import os

random.seed(42)

data = {
    "booking": [
        "I want to book a table for two tonight",
        "Can I reserve a seat for tomorrow evening",
        "I'd like to make a reservation for 4 people",
        "book a slot for this weekend please",
        "I need to schedule an appointment for next Monday",
        "reserve a room for me for two nights",
        "I want to book flight tickets to Lahore",
        "can you book me an order for delivery",
        "I'd like to place a new booking",
        "book an appointment with the doctor",
        "I want to reserve a table for six people",
        "can I schedule a haircut for Saturday",
        "book me a cab for 5pm",
        "I need to make a hotel reservation",
        "reserve two tickets for the concert",
        "can you book a slot for me tomorrow morning",
        "I want to schedule a meeting with the team",
        "book a table near the window please",
        "I'd like to reserve a spot for the workshop",
        "can I book an order for pickup",
        "schedule an appointment with the dentist",
        "book me a table for a birthday dinner",
        "I want to reserve a parking spot",
        "can you book a delivery slot for tomorrow",
        "I'd like to make a new appointment booking",
    ],
    "transfer": [
        "please transfer my call to billing department",
        "can you connect me to a human agent",
        "I need to speak to your manager",
        "transfer me to customer support",
        "put me through to sales team",
        "connect this call to technical support",
        "I want to talk to someone in accounts",
        "redirect my call to the right department",
        "can you forward this to another agent",
        "transfer this to your supervisor",
        "connect me with the complaints department",
        "I need to be transferred to a live representative",
        "put me on hold and connect to support",
        "can you route my call to the right team",
        "transfer me, I need to speak to HR",
        "connect me to the delivery department please",
        "I want to escalate this to a manager",
        "put me through to the finance team",
        "redirect this call to technical help",
        "can someone from support pick up my call",
        "transfer me to the refund department",
        "connect me to a real person please",
        "I need to be forwarded to another line",
        "put me through to the reservations desk",
        "transfer this call to your senior agent",
    ],
    "cancellation": [
        "I want to cancel my booking",
        "please cancel my order",
        "cancel my reservation for tonight",
        "I need to cancel my subscription",
        "cancel my flight ticket please",
        "I don't want the order anymore, cancel it",
        "can you cancel my appointment",
        "I'd like to cancel my membership",
        "cancel this reservation immediately",
        "please remove my booking, I won't come",
        "I want to cancel my table reservation",
        "cancel my delivery order please",
        "I need to cancel my hotel booking",
        "please cancel my meeting for tomorrow",
        "cancel the tickets I booked earlier",
        "I don't need the appointment anymore, cancel it",
        "cancel my ride booking please",
        "I'd like to withdraw my reservation",
        "please cancel my scheduled pickup",
        "cancel my registration for the event",
        "I want to cancel the whole order",
        "please cancel my dinner reservation",
        "cancel my slot for this weekend",
        "I need to call off my booking",
        "please cancel everything I ordered",
    ],
    "modification": [
        "I want to change my booking time",
        "can you reschedule my appointment",
        "I need to modify my order",
        "change my reservation to next week",
        "update my delivery address please",
        "can I change the number of guests in my booking",
        "move my appointment to a later slot",
        "I want to edit my order details",
        "reschedule my flight to next month",
        "change the date of my reservation",
        "can you change my table booking to 8pm",
        "I need to update my phone number on the order",
        "reschedule the meeting to Friday",
        "can I change my seat selection",
        "I want to modify the items in my order",
        "please update my reservation to 6 people",
        "change my pickup time to later",
        "I need to reschedule my dentist appointment",
        "can you move my booking to tomorrow",
        "I want to add an extra guest to my reservation",
        "please change my delivery time",
        "reschedule my ride to a later time",
        "can I update my booking details",
        "change my appointment to next Tuesday",
        "I want to modify my hotel check-in date",
    ],
}

rows = [{"text": phrase, "label": label} for label, phrases in data.items() for phrase in phrases]
df = pd.DataFrame(rows)
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

os.makedirs("data", exist_ok=True)
df.to_csv("data/calls.csv", index=False)

print(df['label'].value_counts())